#!/usr/bin/env php
<?php

declare(strict_types=1);

function print_usage(string $script): void
{
    $name = basename($script);
    fwrite(STDERR, "Usage: php {$name} [--in-memory|--temp-file] <input.phar> <output.php>\n");
    fwrite(STDERR, "Default is: try in-memory first, fallback to temp-file.\n");
}

$loadMode = 'auto';
$positionals = [];

for ($i = 1; $i < $argc; $i++) {
    $arg = $argv[$i];

    if ($arg === '--in-memory') {
        if ($loadMode !== 'auto' && $loadMode !== 'memory') {
            fwrite(STDERR, "Conflicting mode flags provided.\n");
            exit(1);
        }

        $loadMode = 'memory';
        continue;
    }

    if ($arg === '--temp-file') {
        if ($loadMode !== 'auto' && $loadMode !== 'temp') {
            fwrite(STDERR, "Conflicting mode flags provided.\n");
            exit(1);
        }

        $loadMode = 'temp';
        continue;
    }

    $positionals[] = $arg;
}

if (count($positionals) !== 2) {
    print_usage($argv[0] ?? 'pharscript.php');
    exit(1);
}

$inputPhar = $positionals[0];
$outputPhp = $positionals[1];

if (!is_file($inputPhar) || !is_readable($inputPhar)) {
    fwrite(STDERR, "Input PHAR not found or not readable: {$inputPhar}\n");
    exit(1);
}

$pharBinary = file_get_contents($inputPhar);
if ($pharBinary === false) {
    fwrite(STDERR, "Failed to read PHAR: {$inputPhar}\n");
    exit(1);
}

$pharLength = strlen($pharBinary);
$pharSha256 = hash('sha256', $pharBinary);
$sourceName = basename($inputPhar);
$generatedAt = gmdate('c');
$pharAlias = 'embedded-' . substr($pharSha256, 0, 16) . '.phar';

$wrapperTemplate = <<<'PHP'
<?php
declare(strict_types=1);

/*
 * Generated by pharscript.php
 * Source archive: __SOURCE_NAME__
 * Generated at: __GENERATED_AT__
 */

const EMBEDDED_PHAR_LENGTH = __PHAR_LENGTH__;
const EMBEDDED_PHAR_SHA256 = '__PHAR_SHA256__';
const EMBEDDED_PHAR_NAME = '__SOURCE_NAME__';
const EMBEDDED_PHAR_ALIAS = '__PHAR_ALIAS__';
const EMBEDDED_LOAD_MODE = '__LOAD_MODE__';

final class EmbeddedPharMemoryStream
{
    private static string $data = '';
    private int $position = 0;

    public static function setData(string $data): void
    {
        self::$data = $data;
    }

    public function stream_open(string $path, string $mode, int $options, ?string &$opened_path): bool
    {
        if ($mode !== 'rb') {
            return false;
        }

        $this->position = 0;
        return true;
    }

    public function stream_read(int $count): string
    {
        $chunk = substr(self::$data, $this->position, $count);
        $this->position += strlen($chunk);
        return $chunk;
    }

    public function stream_eof(): bool
    {
        return $this->position >= strlen(self::$data);
    }

    public function stream_seek(int $offset, int $whence = SEEK_SET): bool
    {
        $length = strlen(self::$data);

        if ($whence === SEEK_SET) {
            $newPos = $offset;
        } elseif ($whence === SEEK_CUR) {
            $newPos = $this->position + $offset;
        } elseif ($whence === SEEK_END) {
            $newPos = $length + $offset;
        } else {
            return false;
        }

        if ($newPos < 0 || $newPos > $length) {
            return false;
        }

        $this->position = $newPos;
        return true;
    }

    public function stream_tell(): int
    {
        return $this->position;
    }

    public function stream_stat(): array
    {
        return [
            'size' => strlen(self::$data),
            7 => strlen(self::$data),
            'mode' => 0100444,
            2 => 0100444,
        ];
    }

    public function url_stat(string $path, int $flags): array
    {
        return [
            'size' => strlen(self::$data),
            7 => strlen(self::$data),
            'mode' => 0100444,
            2 => 0100444,
        ];
    }
}

(function (): void {
    $stderr = defined('STDERR') ? STDERR : fopen('php://stderr', 'wb');
    $self = __FILE__;

    $in = fopen($self, 'rb');
    if ($in === false) {
        fwrite($stderr, "Failed to open wrapper file for reading.\n");
        exit(1);
    }

    if (fseek($in, __COMPILER_HALT_OFFSET__) !== 0) {
        fclose($in);
        fwrite($stderr, "Failed to seek to embedded PHAR data.\n");
        exit(1);
    }

    $embeddedPhar = stream_get_contents($in);
    fclose($in);

    if ($embeddedPhar === false || strlen($embeddedPhar) !== EMBEDDED_PHAR_LENGTH) {
        fwrite($stderr, "Failed to read embedded PHAR data.\n");
        exit(1);
    }

    if (hash('sha256', $embeddedPhar) !== EMBEDDED_PHAR_SHA256) {
        fwrite($stderr, "Embedded PHAR checksum verification failed.\n");
        exit(1);
    }

    $preferMemory = EMBEDDED_LOAD_MODE !== 'temp';
    $requireMemory = EMBEDDED_LOAD_MODE === 'memory';

    if ($preferMemory && class_exists('Phar', false)) {
        $scheme = 'embeddedpharmem';

        if (!in_array($scheme, stream_get_wrappers(), true)
            && !stream_wrapper_register($scheme, EmbeddedPharMemoryStream::class)) {
            if ($requireMemory) {
                fwrite($stderr, "Failed to register in-memory stream wrapper.\n");
                exit(1);
            }
        } else {
            EmbeddedPharMemoryStream::setData($embeddedPhar);

            $memoryPharPath = $scheme . '://' . EMBEDDED_PHAR_NAME;
            $loaded = false;

            try {
                $loaded = Phar::loadPhar($memoryPharPath, EMBEDDED_PHAR_ALIAS);
            } catch (Throwable $e) {
                $loaded = false;
            }

            if ($loaded) {
                include 'phar://' . EMBEDDED_PHAR_ALIAS . '/.phar/stub.php';
                return;
            }

            if ($requireMemory) {
                fwrite($stderr, "Failed to load embedded PHAR from memory.\n");
                exit(1);
            }
        }
    } elseif ($requireMemory) {
        fwrite($stderr, "Memory mode requested, but Phar support is unavailable.\n");
        exit(1);
    }

    $tmpPhar = rtrim(sys_get_temp_dir(), DIRECTORY_SEPARATOR)
        . DIRECTORY_SEPARATOR
        . 'embedded-' . EMBEDDED_PHAR_SHA256 . '.phar';

    if (file_put_contents($tmpPhar, $embeddedPhar) === false) {
        fwrite($stderr, "Failed to write fallback temp PHAR: " . $tmpPhar . "\n");
        exit(1);
    }

    include $tmpPhar;
})();

__halt_compiler();
PHP;

$wrapperPhp = strtr($wrapperTemplate, [
    '__SOURCE_NAME__' => addslashes($sourceName),
    '__GENERATED_AT__' => addslashes($generatedAt),
    '__PHAR_LENGTH__' => (string) $pharLength,
    '__PHAR_SHA256__' => $pharSha256,
    '__PHAR_ALIAS__' => $pharAlias,
    '__LOAD_MODE__' => $loadMode,
]);

$outputData = $wrapperPhp . $pharBinary;
$bytesWritten = file_put_contents($outputPhp, $outputData);

if ($bytesWritten === false || $bytesWritten !== strlen($outputData)) {
    fwrite(STDERR, "Failed to write wrapper output: {$outputPhp}\n");
    exit(1);
}

@chmod($outputPhp, 0755);
fwrite(STDOUT, "Created wrapper: {$outputPhp}\n");
